### PR TITLE
Stable/Beta -> 2.0.0 & Dev -> 2.1.0-10.0.pre

### PR DESCRIPTION
**Pull request by Bilonik**

### CODE REVIEW

**Review by fkorotkov — CHANGES_REQUESTED** [review]
Probably beta and dev should be also updated to 2.0.0?

**Comment by Bilonik** [comment]
There is no new version for dev and beta 
https://flutter.dev/docs/development/tools/sdk/releases

**Comment by fkorotkov** [comment]
Beta just got updated. I think they will update dev shortly as well. Weird that stable is greater than dev 😅

**Review by fkorotkov — APPROVED** [review]

**Comment by Bilonik** [comment]
Thanks!!

**Comment by fkorotkov** [comment]
Thank you!

**Pull request merged**
