### PR TITLE
Bump stable and dev versions

### PR DESCRIPTION
**Pull request by arthurdenner**

### CODE REVIEW

**Comment by arthurdenner** [comment]
Only build for stable and latest failed for the first commit and (I don't know why) build for dev failed for the second command - it had succeeded for the first. 🤔

**Comment by fkorotkov** [comment]
Thank you!

**Comment by arthurdenner** [comment]
@fkorotkov, no problem. Thank you these images, they are really helpful!

How long does it take to get them available on Docker? I'm asking more out of curiosity and not trying to rush - just to clarify. It seemed like a check published an image if the build was successful but these new images are not available yet, apparently.

**Comment by fkorotkov** [comment]
Once master build finishes. Couple more minutes. 👌

**Pull request merged**
